### ISSUE TITLE
Menu not showing on mobile devices

### ISSUE THREAD

**Issue by siren386** [getgrav/grav-skeleton-photographer-site#3]
Hi!

The top-menu is not showing on mobile-devices or when resizing the browser-window to small.

Best, siren386

![photo](https://cloud.githubusercontent.com/assets/14054474/10542855/536a7d76-741b-11e5-91de-67fef952c557.JPG)

**Comment by rhukster** [comment]
@hexplor i think you will find if you update to the latest Bootsrap version it will work :)

**Comment by hexplor** [comment]
This issue was fixed months ago. I simply forgot to update the demo. Download version is fine. Fixed.
