### ISSUE TITLE
Unable To Disable Modular Content

### ISSUE THREAD

**Issue by LieutenantRice** [getgrav/grav-skeleton-photographer-site#4]
Hey guys,

I'm a fan of your theme, although I am having issues with removing modular content from the home page. I just commented out the custom sections in modular.md, but the section will still show up at the bottom of the page. Like so. 
<img width="381" alt="screen shot 2016-06-13 at 3 08 01 pm" src="https://cloud.githubusercontent.com/assets/7194968/16008564/dc1f76ba-3178-11e6-967a-cda03a707d7f.png">

Here is the site in question. http://beta.thehouseofindie.com/

**Comment by flaviocopes** [comment]
The page cache is cleared / disabled?

**Comment by LieutenantRice** [comment]
It was and I was only able to remove it by actually deleting the folders from the FTP. 
1. Besides that I am unable to add a link to the category boxes. I've tried using both url: and link: and tried routing it to www.facebook.com. But it does nothing, it just adds a '#' to the url I'm currently on.
2. Also I can't seem to find where the footer content can be changed. I know I can update the social media links in site.yaml, but I can't for example change the file name for the logo, or update the privacy policy text to say 2016 instead of 2013.

**Comment by flaviocopes** [comment]
The original issue can only be caused by caching, either in Grav or on another cache level.

The other things are theme specific, and the theme does not support links in the categories. You can see it here, https://github.com/getgrav/grav-theme-photographer/blob/develop/templates/modular/categories.html.twig.

You can check where the footer is defined by opening the user/themes folder in a text editor, and searching for a line present in the footer. This will open up the correct file.

**Comment by LieutenantRice** [comment]
Thanks for the heads up man. Was able to get things working now 😄

**Comment by bobbwal** [comment]
How did you figure out the original issue? I'm having the same problem. I've cleared/disabled the cache, cleared the browser cache, tried private browsing mode. The only way I can hide the sections is by deleting the directories.

**Comment by krsyoung** [comment]
I had this same problem.  I ended up updating the theme to support this (in my case it was Agency).  I added a new property `disabled: true` to the header for the module and then updated the modular template like so:

```
# templates/modular.html.twig
{% block content %}
    {{ page.content }}
    {% for module in page.collection() if module.header.disabled != true %}
        {{ module.content }}
    {% endfor %}
{% endblock %}
```

The key change being `module.header.disabled != true`.  Works like a charm.
