### ISSUE TITLE
Vanilla Install: Contact Fields Not Visible

### ISSUE THREAD

**Issue by duceduc** [getgrav/grav-skeleton-photographer-site#5]
I have tried to install several times the skeleton photographer site and both the contact form fields are not visible on the location and about page.

**Comment by Fe-Lit** [comment]
Hi duceduc,
i can't help you, but i'm experiencing the same problem. Local (win7/xamp) and on a webserver it's not working. Anybody having any suggestions?
Felix

**Comment by flaviocopes** [comment]
The skeleton used the Simple Form plugin which has been discontinued, and removed, by its developer.

Use the Form plugin instead, here is a quick guide on creating a Contact Form: https://learn.getgrav.org/forms/forms/example-form
